### ISSUE TITLE
The file extension should be removed before assigning it to public ID

### ISSUE THREAD

**Issue by reefki** [carlosocarvalho/flysystem-cloudinary#1]
Thanks for creating this adapter, this is exactly what I am looking for. However, when I use `storeAs()` method to use a custom file name instead of using automatically generated one the file extension becomes duplicated.

```
$request->input('image')->storeAs('', 'my-custom-image-name.png', 'cloudinary');

// result
http://res.cloudinary.com/cloudname/image/upload/vXXXXX/my-custom-image-name.png.png
```

**Comment by carlosocarvalho** [comment]
Sorry for the delay, I have not looked at this repository for a while.
I believe you should be using the laravel framework, if that is the case use this provider we have created 

to help with this.https://github.com/carlosocarvalho/laravel-storage-cloudinary

**Comment by tremby** [comment]
I'm seeing duplicate extensions too. I'm not using Laravel.
