### ISSUE TITLE
Problems with read/readStream implementations

### ISSUE THREAD

**Issue by xfynx** [carlosocarvalho/flysystem-cloudinary#12]
Hello!
I'm trying to integrate your library as an adapter for cloudinary in pimcore. I faced the issue with read API implementation.
Looks like [here (link to the code)](https://github.com/carlosocarvalho/flysystem-cloudinary/blob/ceb5d36a817d8bba2cd32c7e3c001c67293e4df7/src/CloudinaryAdapter.php#L248-L263) it tries to read local file instead of fetching from client API.
I tried to replace it with `$this->adminApi->asset($path)` and other ways (including fetching data by url), but it does not work properly for some reason. i'm not really into php to be honest, so maybe i do something wrong and don't get something right 😆 
Also i looked into another similar adapter libraries, such as [webdav](https://github.com/thephpleague/flysystem/blob/3.x/src/WebDAV/WebDAVAdapter.php#L157), [gitlab](https://github.com/RoyVoetman/flysystem-gitlab-storage/blob/master/src/GitlabAdapter.php#L147), [aws](https://github.com/thephpleague/flysystem/blob/36619b549565ff45cb8e8931139de443fcaa34a4/src/AwsS3V3/AwsS3V3Adapter.php#L465) and they doing client API calls.
Maybe i'm wrong and it does right request to API, but it returns errors (in the end. i'm trying to integrate it into pimcore) like `Unable to load image: /tmp/phpwcWaQM` and other related to missing file. Maybe it's really something wrong with Cloudinary library, not your.

Can you manage with it somehow? It would be very helpful for me!
Thanks in advance!

**Comment by carlosocarvalho** [comment]
Hello, this problem is directly linked with cloudinary package.
The method you are using makes a direct call to the cloudinary api.
If you are using version 2 of my package try using the version and see if the problem still happens.
