### ISSUE TITLE
listContents only returns Image resources

### ISSUE THREAD

**Issue by adrian-green** [carlosocarvalho/flysystem-cloudinary#19]
I solved by extending the adapter class with some hackery - would be better if the resource type could be defined in your adapter. No pull req available sorry

- added a property `resourceType` with default value Cloudinary\Asset\AssetType::IMAGE
- added a setter to the class to change the default resource type on the adapter
- overrode the `listContents` method such that it also sends the `resource_type` in the request:

```
$response = (array) $this->adminApi->assets([
    'resource_type' => $this->resourceType,
    'type' => 'upload',
    'prefix' => $directory,
    'max_results' => 500,
    'next_cursor' => isset($response['next_cursor']) ? $response['next_cursor'] : null,
]);
```

**Comment by carlosocarvalho** [comment]
Solved in version 2.0.4
