### ISSUE TITLE
Cloudinary-Tags are not supported

### ISSUE THREAD

**Issue by bastiankoetsier** [carlosocarvalho/flysystem-cloudinary#6]
Hey, 

thank you very much for this adapter-library!

Unfortunately when uploading a new asset, it does not transfer given tags up to cloudinary because of the hardcoding here https://github.com/carlosocarvalho/flysystem-cloudinary/blob/master/src/CloudinaryAdapter.php#L77 
It seems you "recently" changed the options-behaviour anyway (https://github.com/carlosocarvalho/flysystem-cloudinary/commit/3f2c06dce134e0e75874980f6c42b9cddbc710cd) , maybe it makes sense to just pass on the options/merge with some defaults? 
Here is an example from the cloudinary repo https://github.com/cloudinary/cloudinary_php/blob/master/samples/basic/basic.php#L41.

Would you be open to a PR that adds this behaviour? 

Again, thank you very much & greetings from Berlin!

**Comment by carlosocarvalho** [comment]
Hello, sorry for the delay in the response, I am not receiving emails for issues, as I have not responded before.

But you can send your PR

**Comment by carlosocarvalho** [comment]
closing.
