### ISSUE TITLE
Uploading to new folder

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [carlosocarvalho/flysystem-cloudinary#7]
Hey there!

I can't quite seem to work out how to upload to a new directory in Cloudinary. 

Using the S3 Flysystem Adapter I can do something like:

```
$path = 'new-folder/new-subfolder/filename.png';
Storage::disk('s3')->put($path, $validated['file']);
```

But not matter what I try all my files appear to be uploaded to the root of my Media Library in Cloudinary. Am I missing something simple? Thank you in advance!

**Comment by carlosocarvalho** [comment]
Hi, sorry for the delay in responding.
Git is not sending emails with these new issues.
I did a screen casting to show how we do it here to send the files, see if it helps.

![Test upload](https://res.cloudinary.com/carlosocarvalho/image/upload/v1585437340/screens/test-upload-with-lib.gif)
